### Create User
POST http://localhost:3000/users
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "admin123",
  "name": "Admin",
  "isActive": true,
  "isAdmin": true
}

### Update User
PATCH http://localhost:3000/users/4db3d6e2-e584-44a0-843d-001b370ee6b1
Content-Type: application/json

{
  "name": "Admin"
}

### Get Users
GET http://localhost:3000/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYzA3YzY4NS1iM2EyLTRjOTktYTUyNy05YmJlYjIwMGI4OGIiLCJ1c2VybmFtZSI6InNpZ25lZHVwdXNlckBleGFtcGxlLmNvbSIsImlhdCI6MTc1NTAzODk1MCwiZXhwIjoxNzU1MDQyNTUwfQ.IG5cdjI2R7GA8FX5QfbKoxgCefEbEoFTLL0Mxxr8acE

### Get User by ID
GET http://localhost:3000/users/4db3d6e2-e584-44a0-843d-001b370ee6b1

### Delete User
DELETE http://localhost:3000/users/4db3d6e2-e584-44a0-843d-001b370ee6b1
